### ISSUE TITLE
Missing requirements `adjustText` and `CatChemi`

### ISSUE THREAD

**Issue by arosen93** [sudarshanv01/newns-anderson#2]
You may wish to update your `requirements.txt` to the following, as it's missing the bottom two dependencies. After this, and noting that `python-flint` (a `CatChemi` dependency) can be installed with conda but not pip (see [here](https://github.com/fredrik-johansson/python-flint/issues/23)), everything is good to go!
```
numpy
scipy
matplotlib
ase
PyYAML
mpmath
adjustText
git+https://github.com/sudarshanv01/CatChemi.git
```

**Comment by sudarshanv01** [comment]
Thank you!
